name: Continuous integration
on: [push, pull_request]
jobs:
  prepare-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v2

      - name: Go cache
        uses: actions/cache@v2
        id: gocache
        with:
          path: |
            ${{ env.GO_CACHE }}
            ${{ env.GO_MODULES_CACHE }}
          key: ${{ runner.os }}-gocache-${{ env.GO_VERSION }}${{ hashFiles('go.mod', 'go.sum') }}

      - name: Fill cache
        if:  steps.gocache.outputs.cache-hit != 'true'
        run: go mod download -x
  tests:
    needs: prepare-cache
    strategy:
      matrix:
        go: [ '1.16' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: mdbx
        run: |
          cd ethdb/mdbx/dist/
		      make clean && make config.h
		      echo '#define MDBX_DEBUG 0' >> config.h
		      echo '#define MDBX_FORCE_ASSERTIONS 0' >> config.h
		      echo '#define MDBX_ENABLE_MADVISE 0' >> config.h
          echo '#define MDBX_TXN_CHECKOWNER 1' >> config.h
          echo '#define MDBX_ENV_CHECKPID 1' >> config.h
          echo '#define MDBX_DISABLE_PAGECHECKS 0' >> config.h
          CFLAGS_EXTRA="-Wno-deprecated-declarations" make mdbx-static.o
      - name: tidy
        run: |
          go mod tidy
          test -z "$(git status --porcelain)"
      - name: test
        run: make test
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --config=./.golangci/step1.yml
